### PR TITLE
Added some content models that do not have any DSIDs.

### PR DESCRIPTION
**Pull request by mjordan**
I'd like to use this module to support additional content models, but some of the cmodels I'm interested in don't have any datastreams that are suitable to add to the `$cmodel_dsids` array. I can't figure out what the function of the DSID is.... so just for kicks I've added some members to the `$cmodels_dsids` array that use NULL as the DSID, and after adding my new content models, calls like `http://localhost:8000/islandora_usage_stats_callbacks/object_stats/islandora:182` (islandora:182 is a compound object) continue to work:

```
{
   "pid":"islandora:182",
   "cmodel":"islandora:compoundCModel",
   "legacy-views":0,
   "legacy-downloads":0,
   "views":[
      {
         "time":"1496415570"
      },
      {
         "time":"1496761323"
      },
      {
         "time":"1496844801"
      },
      {
         "time":"1496858908"
      }
   ],
   "downloads":[

   ]
}
```

Is it OK to add new content models and use NULL where applicable?

### CODE REVIEW

**Comment by bryjbrown** [comment]
@mjordan I like this, but I think the code as-is is going to cause some problems. This array that you have edited informs the building of the `$ids` variable, which stores the "downloads" datastream as `$ids['dsid']` (set at https://github.com/FLVC/islandora_usage_stats_callbacks/blob/master/islandora_usage_stats_callbacks.module#L118)

Then, `$ids['dsid']` is used as part of a SQL query to count up the number of datastream accesses, and if we dump FALSE or NULL in there it will cause problems (see at https://github.com/FLVC/islandora_usage_stats_callbacks/blob/master/islandora_usage_stats_callbacks.module#L147)

My recommendation would be to change the NULL values in the array to FALSE, and then have some sort of boolean check on https://github.com/FLVC/islandora_usage_stats_callbacks/blob/master/islandora_usage_stats_callbacks.module#L53

for instance:
```
$report['downloads'] = ($ids['dsid'] ? islandora_usage_stats_callbacks_get_object_downloads($ids) : FALSE;
```
This would check to see if `$ids['dsid']` is FALSE, and if it is, don't even engage the SQL query and just return FALSE instead. You'd need to make sure whatever service you were using to consume this usage stats JSON feed knew how to handle that response, but seems like the right way to go.

I'd also like make sure this gets tested to ensure that it behaves the way we expect before merging.

Sound good?

**Comment by mjordan** [comment]
Thanks,sounds good. I'll push some updates to my branch in the next few days.

**Comment by mjordan** [comment]
I've added all the core content models to the `$cmodels_dsids` array using `FALSE` for the DSID where applicable, and have incorporated the logic you suggested in the get_object_stats() function. I then tested as follows:

In my feature branch I issued a request for the stats report for a basic image object (with 2 downloads):

{"pid":"islandora:3","cmodel":"islandora:sp_basic_image","legacy-views":0,"legacy-downloads":0,"views":[{"time":"1490032394"},{"time":"1494082393"},{"time":"1494082702"},{"time":"1494174388"},{"time":"1494175396"},{"time":"1494176227"},{"time":"1494177243"},{"time":"1494178082"},{"time":"1494193640"},{"time":"1494194645"},{"time":"1494195070"},{"time":"1494253374"},{"time":"1494253718"},{"time":"1494255836"},{"time":"1494298242"},{"time":"1494529800"},{"time":"1494530249"},{"time":"1494531041"},{"time":"1494531440"},{"time":"1494531804"},{"time":"1494532170"},{"time":"1496931163"},{"time":"1496931541"}],"downloads":[{"time":"1496931173"},{"time":"1496931541"}]}

This response is identical to the same request in the master branch:


{"pid":"islandora:3","cmodel":"islandora:sp_basic_image","legacy-views":0,"legacy-downloads":0,"views":[{"time":"1490032394"},{"time":"1494082393"},{"time":"1494082702"},{"time":"1494174388"},{"time":"1494175396"},{"time":"1494176227"},{"time":"1494177243"},{"time":"1494178082"},{"time":"1494193640"},{"time":"1494194645"},{"time":"1494195070"},{"time":"1494253374"},{"time":"1494253718"},{"time":"1494255836"},{"time":"1494298242"},{"time":"1494529800"},{"time":"1494530249"},{"time":"1494531041"},{"time":"1494531440"},{"time":"1494531804"},{"time":"1494532170"},{"time":"1496931163"},{"time":"1496931541"}],"downloads":[{"time":"1496931173"},{"time":"1496931541"}]}


In my feature branch I issued a request for the usage report for a compound object (i.e., one of the new cmodels with a FALSE DSID):

{"pid":"islandora:182","cmodel":"islandora:compoundCModel","legacy-views":0,"legacy-downloads":0,"views":[{"time":"1496415570"},{"time":"1496761323"},{"time":"1496844801"},{"time":"1496858908"},{"time":"1496929502"},{"time":"1496931607"}],"downloads":[]}

This response is valid JSON.

Question: The "legacy-downloads" has a value of 0 by defult. We are producing an empty list (`[]`) as the value for "downloads" if the content model has a DSID of FALSE. Is this inconsistency important?

**Comment by bryjbrown** [comment]
@mjordan The `legacy-stats` data is for shoehorning in aggregated view/download counts from previous systems, its a bit of hack tho. It doesn't have time/ip data for each event, just an integer, so its correct for it to return `0` but for downloads to return an empty array. Our production system is running `count()` on the `downloads` array, so we need to it stick with an empty array for consistency.

Aside from that, this PR looks good! Thanks for doing testing on your end. I'll do some testing on my end as well and then will merge. :+1: Thanks!

**Comment by mjordan** [comment]
Just noticing now (four months later) that there are some merge conflicts. Wanme to resolve and update this PR?

**Comment by bryjbrown** [comment]
@mjordan Ha! I totally forgot about this PR, my apologies. I think the merge conflict is due to a PR from @bondjimbond that was merged a few days before this PR was filed (but probably after you made a fork). The conflict is around the list of cmodels and their download datastreams, so this should be very easy to fix. Since you offered (and are the author of the PR), I'll let you take first crack at it. LMK if you would like any assistance.

**Comment by bondjimbond** [comment]
Thanks for doing this, @mjordan! It'd be great to have all CModels covered.

Can I add one more review note? I see that for the Newspaper Issue and Book CModels, you have set them to FALSE -- but there are many cases where there is a PDF datastream available to download (although at the moment you'd need something like Islandora Downloadable Datastreams to expose it publicly). I'd love for those to be included in the count.

I imagine that this module already handles such cases, since Citations and Theses PDF datastreams aren't actually required. So for Newspaper Issue and Book, you could probably just change "FALSE" to "PDF" and it should work just fine.

**Comment by bryjbrown** [comment]
@bondjimbond is correct, if an object is missing its downloadable datastream, then it will just have an empty download array (`"downloads":[]`)

**Comment by bondjimbond** [comment]
@mjordan Possibly out of scope, but it would be nice to be able to track downloads of different datastreams for certain CModels. For some of these, a repository might not expose the OBJ to download, but instead a smaller derivative. For example:

- Large image: JP2, JPG
- Audio: PROXY_MP3
- Video: MP4, MKV
- Basic Image: MEDIUM_SIZE

In fact, there are repositories that delete OBJs and only keep the derivatives.

Would it be possible to make Usage Stats Callbacks display aggregated results for every derivative? Or just add configurable datastream choices to the admin form, with the ones you added as defaults?

**Comment by bryjbrown** [comment]
@bondjimbond I'd say that setting the "Download" datastream from an admin menu on a per cmodel basis would be the least complicated option. Trying to set up aggregation for multiple datastreams sounds like a headache.

**Comment by bondjimbond** [comment]
@bryjbrown I agree... simpler is better, and if you give people access to one download, it's not SUPER likely that they'll choose another (except perhaps in case of newspaper pages and book pages). 

If @mjordan doesn't want to make the configurable feature part of this PR, I could prod at it after this is merged.

**Comment by mjordan** [comment]
I can correct the conflicts today, and fix the `FALSE` values, but @bondjimbond if you're willing to look into the new feature, it's yours!

I have to say that hard-coding content models is a bit of a maintenance PITA, since some sites may have custom content models. Maybe we should provide a `drupal_alter()` that lets local admins add new cmodels to the array with some simple code?

**Comment by bondjimbond** [comment]
@mjordan Do you know if it's possible to get the list of installed cmodels using islandora_get_content_models() (e.g. the [Islandora Badges admin form](https://github.com/Islandora/islandora_badges/blob/7.x/includes/admin.form.inc#L14-L16)), and use that output in the admin form to configure custom DSIDs?

This is a feature I'd also love to add to islandora_downloadable_datastreams.

**Comment by mjordan** [comment]
@bondjimbond Sounds possible. Would https://github.com/Islandora/islandora/blob/7.x/includes/utilities.inc#L402 be of some use?

**Comment by bryjbrown** [comment]
I never thought there would be much community interest in this module, but if @mjordan and @bondjimbond think it would be a good idea I could contribute this to the foundation and it could become an Islandora Labs module. If at least 3 people are using it, then I have qualms about keeping it sequestered in the FLVC repo.

**Comment by mjordan** [comment]
OK, I finally wrestled those merge conflicts to the ground. Please review at your convenience.

**Comment by bondjimbond** [comment]
@bryjbrown Maybe after all of these suggestions are finished. Y'know, for expediency. 😁

**Comment by bondjimbond** [comment]
@mjordan Hmm... undrestanding/parsing that will take me some time.

**Comment by mjordan** [comment]
@bondjimbond I'd have to implement it in a module and inspect its output, which I will do this evening, to offer additional explanation. @bryjbrown do you want us to continue this side convo here or elsewhere?

**Comment by mjordan** [comment]
@bryjbrown I have merged @bondjimbond 's updates into this branch and will do one more round of smoke testing before handing it over to you for your own tests and hopefully merge. @bondjimbond 's changes replaced my original ones entirely, so at this point, this PR is just a proxy for his work :smile:

**Comment by mjordan** [comment]
OK, I added an entry for a new content type, islandora:sp_remote_resource (managed by [this module](https://git.lib.sfu.ca/mjordan/islandora_solution_pack_remote_resource)) and then used the callbacks module to get a report on its hits. It worked! Here's what I got back:

```json
{"pid":"testing:43","cmodel":"islandora:sp_remote_resource","legacy-views":0,"legacy-downloads":0,"views":[{"time":"1506182916"},{"time":"1506264544"},{"time":"1506274703"},{"time":"1506275013"},{"time":"1506275496"},{"time":"1506275941"},{"time":"1506287361"},{"time":"1506288134"},{"time":"1506288638"},{"time":"1506289065"},{"time":"1506289492"},{"time":"1506348397"},{"time":"1506349686"}],"downloads":[]}
```
Sweet. Nice work @bondjimbond.

Over to you @bryjbrown.

**Comment by bryjbrown** [comment]
Awesome job, @mjordan and @bondjimbond. I just tested on my machine and it works as expected, and fails gracefully with mispelled cmodels and dsids. :+1:

**Pull request merged**
